# Generated by Django 4.1.3 on 2022-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='riders',
            field=models.ManyToManyField(to='races.rider'),
        ),
    ]
