# Generated by Django 4.1.3 on 2022-12-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_race_riders'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rider',
            name='password',
            field=models.CharField(default='0000', max_length=16),
        ),
    ]
