# Generated by Django 4.1.1 on 2022-12-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_rename_friend_request_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(default='', max_length=24, unique=True),
        ),
    ]
