# Generated by Django 4.1.1 on 2022-12-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_alter_race_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='owned_races',
            field=models.ManyToManyField(blank=True, related_name='owned_races', to='races.race'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='participating_races',
            field=models.ManyToManyField(blank=True, related_name='participating_races', to='races.race'),
        ),
    ]
