# Generated by Django 4.1.1 on 2022-12-20 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_myuser_owned_races_myuser_participating_races'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
